const { pool } = require('../../config/db');

const createMstUdiseTeacher = async () => {
    const query = `CREATE TABLE IF NOT EXISTS public.mst_udise_teacher
(
    id SERIAL PRIMARY KEY,
    udise_sch_code bigint,
    emp_staff_id bigint,
    ac_year character varying(255),
    emp_name character varying(255),
    gender character varying(50),
    dob character varying(50),
    emp_code_state character varying(255),
    social_cat character varying(100),
    qual_acad character varying(255),
    trade character varying(255),
    qual_prof character varying(255),
    mobile character varying(20),
    email character varying(255),
    math_upto character varying(255),
    science_upto character varying(255),
    english_upto character varying(255),
    soc_study_upto character varying(255),
    lang_study_upto character varying(255),
    nature_of_appt character varying(255),
    disability_type character varying(255),
    crr_no character varying(100),
    doj_service date,
    emp_name_per_uid character varying(255),
    tch_type character varying(100),
    doj_ps character varying(50),
    class_taught character varying(100),
    appointed_level character varying(100),
    appt_sub character varying(255),
    sub_taught1 character varying(255),
    sub_taught2 character varying(255),
    tch_deputation character varying(10),
    tch_from_other_school character varying(10),
    trained_cwsn character varying(10),
    trained_comp character varying(10),
    trng_rcvd character varying(255),
    trng_needed character varying(255),
    trg_nishtha character varying(255),
    nontch_days character varying(50),
    main_lang_1 character varying(100),
    main_lang_2 character varying(100),
    main_lang_3 character varying(100),
    tr_ssa_yn character varying(10),
    cy_psy_soc_aspect_yn character varying(10),
    rece_training_support_cwsn_yn character varying(10),
    is_ctet_stet character varying(10),
    ctet_stet character varying(100),
    is_capable_vc character varying(10),
    uid_masking character varying(10),
    is_uid_verified character varying(10),
    response_code character varying(100),
    verification_date character varying(50),
    nat_tch_id character varying(255),
    form_flag bigint,
    aadhaar_provided character varying(10)
);`;
    await pool.query(query);
};

module.exports = { createMstUdiseTeacher };